# Generated by Django 3.2.13 on 2022-05-31 04:06

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='company name')),
                ('advertisement_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='광고 URL ')),
                ('level', models.IntegerField(default=0, verbose_name='user level')),
                ('unique_id', models.CharField(blank=True, max_length=50, verbose_name='google Id')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None, unique=True, verbose_name='mobile phone number')),
                ('naver_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='naver api Key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('salt', models.CharField(blank=True, max_length=10, verbose_name='Salt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저 목록',
                'ordering': ('-created_at',),
            },
        ),
    ]
