# Generated by Django 3.2.13 on 2022-05-31 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_qc_cnt', models.IntegerField(default=0, verbose_name='검색량_전체')),
                ('monthly_pc_qc_cnt', models.IntegerField(default=0, verbose_name='검색량_pc')),
                ('monthly_mobile_qc_cnt', models.IntegerField(default=0, verbose_name='검색량_모바일')),
                ('monthly_ave_clk_cnt', models.FloatField(default=0, verbose_name='클릭수_전체')),
                ('monthly_ave_pc_clk_cnt', models.FloatField(default=0, verbose_name='클릭수_pc')),
                ('monthly_avg_mobile_clk_cnt', models.FloatField(default=0, verbose_name='클릭수_모바일')),
                ('monthly_ave_ctr', models.FloatField(default=0, verbose_name='클릭률_전체')),
                ('monthly_ave_pc_ctr', models.FloatField(default=0, verbose_name='클릭률_PC')),
                ('monthly_ave_mobile_ctr', models.FloatField(default=0, verbose_name='클릭률_모바일')),
                ('pl_avg_depth', models.IntegerField(default=0, verbose_name='월평균노출_광고수')),
                ('comp_idx', models.CharField(default='', max_length=15, verbose_name='경쟁강도')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_keywords', to='keywords.keyword')),
            ],
        ),
    ]
